name: CI
on:
  push:
  pull_request:

jobs:
  check-semantics-local:
    name: 'Check Semantics (local)'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get package manager
        uses: ./

  check-semantics-main:
    name: 'Check Semantics (main)'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get package manager
        uses: GarnerCorp/build-actions/install-package-manager@add-install-pkg-manager
